#!/usr/bin/env bash

REPO="$HOME/.backup"
BIN_PATH=/usr/local/bin/backup
SERICE_PATH=/usr/lib/systemd/user

echo -n "=> Check if systemd exists..."
pidof systemd &> /dev/null
if [ $? -eq 0 ]; then
    echo "Yes"
else
    echo "No"
fi

echo -n "=> Check if borg exists..."
if [ -f "/usr/bin/borg" ]; then
    echo "Yes"
else
    echo "No"
fi

echo -n "=> Check if rclone exists..."
if [ -f "/usr/bin/rclone" ]; then
    echo "Yes"
else
    echo "No"
fi

echo "=> Create repository"
borg init --encryption=none ${REPO}

echo "=> Copy backup script"
sudo cp -u ./backup $BIN_PATH

echo "=> Setting permissions"
sudo chmod u+x $BIN_PATH

echo "=> Copy systemd unit files"
sudo cp -u backup.service $SERICE_PATH
sudo cp -u backup.timer $SERICE_PATH

echo "=> Reload systemd unit files"
systemctl --user daemon-reload

echo "=> Enable the backup timer"
systemctl --user enable backup.timer
