#!/usr/bin/env bash

REPO="$HOME/.backup"
BIN_PATH=/usr/local/bin/backup
SERICE_PATH=/usr/lib/systemd/user

echo "=> Create repository"
borg init --encryption=none ${REPO}

echo "=> Copy backup script"
sudo cp -u ./backup $BIN_PATH

echo "=> Setting permissions"
sudo chmod u+x $BIN_PATH

echo "=> Copy systemd unit files"
sudo cp -u backup.service $SERICE_PATH
sudo cp -u backup.timer $SERICE_PATH

echo "=> Reload systemd unit files"
sudo systemctl daemon-reload

echo "=> Enable the backup timer"
systemctl --user enable backup.timer
