version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - run:
          name: Install dependencies
          command: |
              apt-get update &&\
              apt-get install -y git systemd borgbackup rclone curl &&\
              mkdir -p "$HOME/.config/backup/" &&\
              echo "$HOME" > "$HOME/.config/backup/backuprc"
      - checkout
      - run:
          name: Configuring dependencies
          command: |
            sed -i 's/sudo//g' install uninstall
      - run:
          name: Test install script
          command: bash -x install -a

      - run:
          name: Test backup script 
          command: bash -x backup